const list = [
  {
    id: "fullstack",
    head: "Top Differences: Full Stack Developer vs Software Engineer 2024",
    cont: "A Full Stack Developer is a tech all-rounder. They work on both the front and back",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Full-Stack-Developer-vs-Software-Engineer-.webp",
  },
  {
    id: "fullstack",
    head: "Horizontal vs Vertical Scaling for Efficient System Design",
    cont: "In the world of system design, envision a digital skyscraper – a multifaceted structure built",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Horizontal-vs-Vertical-Scaling-for-Efficient-System-Design.webp",
  },
  {
    id: "fullstack",
    head: "Top 10 Tools Every Full-Stack Developer Should Master in 2024",
    cont: "‍As a full-stack developer, having the right set of tools is crucial for your success.",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Full-Stack-Developer-vs-Software-Engineer-.webp",
  },
  {
    id: "fullstack",
    head: "The Ultimate Guide to Real-World Full-Stack Development Applications",
    cont: "Full-stack development has become increasingly popular in recent years, with companies seeking professionals who can",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Horizontal-vs-Vertical-Scaling-for-Efficient-System-Design.webp",
  },
  {
    id: "fullstack",
    head: "Top Skills To Become a Full-Stack Developer in 2024",
    cont: "Are you interested in becoming a great full-stack developer? If so, then you’re at the",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Full-Stack-Developer-vs-Software-Engineer-.webp",
  },
  {
    id: "fullstack",
    head: "Top 10 Full-Stack Developer Frameworks in 2024",
    cont: "In the ever-evolving world of technology, the demand for full stack developers is at an",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Horizontal-vs-Vertical-Scaling-for-Efficient-System-Design.webp",
  },
  {
    id: "fullstack",
    head: "Best Full-Stack Development Project Ideas in 2024",
    cont: "When you give your resume to any potential recruiter, the first thing that they check",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Full-Stack-Developer-vs-Software-Engineer-.webp",
  },
  {
    id: "fullstack",
    head: "5 Career Opportunities for Full Stack Development",
    cont: "Ever wondered what awesome job opportunities are waiting for you in the field of Full Stack Development? Well, this blog is just for you!",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Horizontal-vs-Vertical-Scaling-for-Efficient-System-Design.webp",
  },
  {
    id: "fullstack",
    head: "Top Full-Stack Developer Skills in 2024",
    cont: "Are you a full-stack developer? Can you name a Website/App you like the most from the",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Full-Stack-Developer-vs-Software-Engineer-.webp",
  },
  {
    id: "datascience",
    head: "Top 10 High Paying Non-Coding Jobs in Data Science in 2024",
    cont: "Are you someone who’s not interested in coding, but wants to get placed in tech",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-Top-High-Paying-Non-Coding-Jobs-in-Data-Science.webp",
  },
  {
    id: "datascience",
    head: "Impact of Certification Programs on Hiring Data Scientists",
    cont: "Data scientists are the creators behind transforming the raw data into edible data insights. These",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-1-1536x768.webp",
  },
  {
    id: "datascience",
    head: "Top Product-Based Companies for Data Science Freshers",
    cont: "In today’s data-driven world, data science has emerged as a crucial field, with companies harnessing",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/feature-image-product-based-companies-for-data-science-freshers.webp",
  },
  {
    id: "datascience",
    head: "What is the Difference between Data Science and Data Engineering?",
    cont: "India has been making some serious waves in the world of data. Just like the",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/10/Feature-image-Difference-between-Data-Science-and-Data-Engineering.webp",
  },
  {
    id: "datascience",
    head: "Roles and Responsibilities of a Data Scientist",
    cont: "‍Data science is a rapidly growing field that has become essential for businesses to thrive",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Feature-image-1-1536x768.webp",
  },
  {
    id: "datascience",
    head: "Extraordinary Data Science Projects for Beginners As Well as Veterans",
    cont: "As the demand for data and the people that can conquer it, i.e. Data Scientists",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/feature-image-product-based-companies-for-data-science-freshers.webp",
  },
  {
    id: "datascience",
    head: "How to become a Data Scientist after Mechanical Engineering?",
    cont: "Switching careers can sound quite intimidating especially when you’re a mechanical engineer by educational qualification,",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/feature-image-product-based-companies-for-data-science-freshers.webp",
  },
  {
    id: "cyber",
    head: "Non-Coding Jobs in Cybersecurity: A Comprehensive Guide",
    cont: "In the rapidly evolving field of cybersecurity, there is a common misconception that coding skills",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Non-Coding-Jobs-in-Cybersecurity.webp",
  },
  {
    id: "cyber",
    head: "Cybersecurity Vs Ethical Hacking",
    cont: "Cybersecurity & Ethical hacking and have been key in making sure that your data online",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/09/Feature-image-What-Is-Hacking_-Types-of-Hacking-More.webp",
  },
  {
    id: "cyber",
    head: "How Is Cyber Security Important To Our Lives?",
    cont: "Cybersecurity is an exact solution that is sought either by a billionaire with a massive",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Non-Coding-Jobs-in-Cybersecurity.webp",
  },
  {
    id: "cyber",
    head: "The Ultimate Cybersecurity Roadmap for Beginners",
    cont: "Cybersecurity jobs are also one of the most handsomely paying jobs in recent times. Furthermore,",
    img: "https://www.guvi.in/blog/wp-content/uploads/2021/03/The-Ultimate-%E2%80%A8Cybersecurity-Roadmap-for-Beginners.webp",
  },
  {
    id: "cyber",
    head: "The Cybersecurity Surge: 5 Must-Have Cybersecurity Certifications!",
    cont: "There is something fascinating about a lone hacker in black hoodies using a single system",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Non-Coding-Jobs-in-Cybersecurity.webp",
  },
  {
    id: "cyber",
    head: "Cybersecurity vs Artificial Intelligence | Better Career",
    cont: "Cybersecurity is an exponentially growing industry that is evolving to protect individuals & organizations from",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/09/Feature-image-What-Is-Hacking_-Types-of-Hacking-More.webp",
  },
  {
    id: "career",
    head: "UI/UX Designer Job Description and Roles & Responsibilities",
    cont: "UI UX is the abbreviated word that’s been rocking the trend over the years, especially",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Top-IT-Jobs-for-Commerce-Students.webp",
  },
  {
    id: "careerr",
    head: "Top 5 IT Jobs for Economics Students",
    cont: "In today’s digital age, the intersection of economics and technology offers exciting career opportunities for",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Top-IT-Jobs-for-Economics-Students.webp",
  },
  {
    id: "career",
    head: "Top IT Jobs for Commerce Students: A Lucrative Career Path",
    cont: "With the rapid advancement of technology, the demand for IT professionals has soared in recent",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Top-IT-Jobs-for-Commerce-Students.webp",
  },
  {
    id: "career",
    head: "9 Best Product-Based Companies for Project Management",
    cont: "In today’s tech-driven world, the demand for project managers is higher than before. The workload",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/Featured-Image-1536x804.webp",
  },
  {
    id: "career",
    head: "Professional Civil Engineer Resume: A Guide To Attract Employers in 2024",
    cont: "The world is moving towards modernization leading to an increase in the popularity of civil",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/11/FEATURE-IMAGE-1-3-1536x804.webp",
  },
  {
    id: "career",
    head: "Automation Test Engineer Resume: 10 Important Things To Consider",
    cont: "The world is moving towards automating the testing of products in order to increase work",
    img: "https://www.guvi.in/blog/wp-content/uploads/2023/12/Feature-image-Automation-Test-Engineer-Resume-Important-Things-To-Consider.webp",
  },
  ];

export {list};
